server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.12.154.50:3306/12306?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 0909wz
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
  mail:
    host: smtp.qq.com
    username: 2464754760@qq.com
    password: qwmhvsbmqwgrdifa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qf.pojo
